openapi: 3.1.0
info:
  title: Link Shortener API
  description: A simple URL shortener with Microsoft Entra ID authentication
  version: 1.0.0
paths:
  /api/links:
    get:
      tags:
      - Links
      - links
      summary: Get Links
      description: Get all links for the authenticated user's tenant.
      operationId: get_links_api_links_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/LinkResponse'
                type: array
                title: Response Get Links Api Links Get
      security:
      - HTTPBearer: []
    post:
      tags:
      - Links
      - links
      summary: Create Link
      description: Create a new shortened link.
      operationId: create_link_api_links_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LinkCreate'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LinkResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
  /api/links/{link_id}:
    get:
      tags:
      - Links
      - links
      summary: Get Link
      description: Get a specific link by ID.
      operationId: get_link_api_links__link_id__get
      security:
      - HTTPBearer: []
      parameters:
      - name: link_id
        in: path
        required: true
        schema:
          type: string
          title: Link Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LinkResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    put:
      tags:
      - Links
      - links
      summary: Update Link
      description: Update a link's description.
      operationId: update_link_api_links__link_id__put
      security:
      - HTTPBearer: []
      parameters:
      - name: link_id
        in: path
        required: true
        schema:
          type: string
          title: Link Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LinkUpdate'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LinkResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      tags:
      - Links
      - links
      summary: Delete Link
      description: Delete a link.
      operationId: delete_link_api_links__link_id__delete
      security:
      - HTTPBearer: []
      parameters:
      - name: link_id
        in: path
        required: true
        schema:
          type: string
          title: Link Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/links/{link_id}/analytics:
    get:
      tags:
      - Links
      - links
      summary: Get Link Analytics
      description: Get analytics for a specific link.
      operationId: get_link_analytics_api_links__link_id__analytics_get
      security:
      - HTTPBearer: []
      parameters:
      - name: link_id
        in: path
        required: true
        schema:
          type: string
          title: Link Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalyticsResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /:
    get:
      tags:
      - Health
      - system
      summary: Root
      description: Root endpoint.
      operationId: root__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                title: Response Root  Get
  /api/health:
    get:
      tags:
      - Health
      - system
      summary: Health Check
      description: Health check endpoint.
      operationId: health_check_api_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
  /health:
    get:
      tags:
      - Health
      - system
      summary: Health Check
      description: Health check endpoint.
      operationId: health_check_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
  /{short_code}:
    get:
      tags:
      - Redirects
      - redirect
      summary: Redirect To Original
      description: Redirect to the original URL using the short code.
      operationId: redirect_to_original__short_code__get
      parameters:
      - name: short_code
        in: path
        required: true
        schema:
          type: string
          title: Short Code
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    AnalyticsResponse:
      properties:
        link_id:
          type: string
          title: Link Id
        total_clicks:
          type: integer
          title: Total Clicks
        clicks_today:
          type: integer
          title: Clicks Today
        clicks_this_week:
          type: integer
          title: Clicks This Week
        clicks_this_month:
          type: integer
          title: Clicks This Month
        recent_clicks:
          items:
            $ref: '#/components/schemas/ClickResponse'
          type: array
          title: Recent Clicks
          default: []
      type: object
      required:
      - link_id
      - total_clicks
      - clicks_today
      - clicks_this_week
      - clicks_this_month
      title: AnalyticsResponse
      description: Model for analytics response.
    ClickResponse:
      properties:
        id:
          type: string
          title: Id
        link_id:
          type: string
          title: Link Id
        clicked_at:
          type: string
          format: date-time
          title: Clicked At
        ip_address:
          type: string
          title: Ip Address
        user_agent:
          anyOf:
          - type: string
          - type: 'null'
          title: User Agent
      type: object
      required:
      - id
      - link_id
      - clicked_at
      - ip_address
      title: ClickResponse
      description: Model for click tracking response.
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    HealthResponse:
      properties:
        status:
          type: string
          title: Status
        timestamp:
          type: string
          title: Timestamp
        version:
          type: string
          title: Version
        environment:
          type: string
          title: Environment
        services:
          type: object
          title: Services
          default: {}
        system:
          type: object
          title: System
          default: {}
      type: object
      required:
      - status
      - timestamp
      - version
      - environment
      title: HealthResponse
      description: Model for health check response.
    LinkCreate:
      properties:
        original_url:
          type: string
          title: Original Url
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
        custom_short_code:
          anyOf:
          - type: string
          - type: 'null'
          title: Custom Short Code
      type: object
      required:
      - original_url
      title: LinkCreate
      description: Model for creating a new link.
    LinkResponse:
      properties:
        id:
          type: string
          title: Id
        original_url:
          type: string
          title: Original Url
        short_code:
          type: string
          title: Short Code
        short_url:
          type: string
          title: Short Url
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
        click_count:
          type: integer
          title: Click Count
          default: 0
        created_at:
          type: string
          format: date-time
          title: Created At
        created_by:
          type: string
          title: Created By
        created_by_name:
          anyOf:
          - type: string
          - type: 'null'
          title: Created By Name
        tenant_id:
          type: string
          title: Tenant Id
      type: object
      required:
      - id
      - original_url
      - short_code
      - short_url
      - created_at
      - created_by
      - tenant_id
      title: LinkResponse
      description: Model for link response.
    LinkUpdate:
      properties:
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
      type: object
      title: LinkUpdate
      description: Model for updating a link.
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
