"""Initial database schema with string IDs

Revision ID: d9aebb722252
Revises: 
Create Date: 2025-07-29 13:39:23.264858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9aebb722252'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('short_code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_by_name', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_code')
    )
    op.create_table('clicks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.String(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes for better performance
    op.create_index('idx_links_short_code', 'links', ['short_code'])
    op.create_index('idx_links_tenant', 'links', ['tenant_id'])
    op.create_index('idx_clicks_link_id', 'clicks', ['link_id'])
    op.create_index('idx_clicks_date', 'clicks', ['clicked_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clicks')
    op.drop_table('links')
    # ### end Alembic commands ###
